/* eslint-disable max-len */
export const i18n_SETUP = 'i18n_SETUP';

// LOGIN TYPES
export const CHECK_TFA              = 'CHECK_TFA';
export const CODE_CHANGED           = 'CODE_CHANGED';
export const LOGGED_OUT             = 'LOGGED_OUT';
export const LOGIN_ATTEMPT          = 'LOGIN_ATTEMPT';
export const LOGIN_FAIL_MESSAGE     = 'LOGIN_FAIL_MESSAGE';
export const LOGIN_FAIL_INPUTS      = 'LOGIN_FAIL_INPUTS';
export const LOGIN_SUCCESS          = 'LOGIN_SUCCESS';
export const LOGIN_FAILED           = 'LOGIN_FAILED';
export const PASSWORD_CHANGED       = 'PASSWORD_CHANGED';
export const RESET_LOGIN_INPUTS     = 'RESET_LOGIN_INPUTS';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const SAVE_USER              = 'SAVE_USER';
export const USERNAME_CHANGED       = 'USERNAME_CHANGED';
export const PUSH_PERMIT            = 'PUSH_PERMIT';

// COMMON TYPES
export const LOCALE_LOADED           = 'LOCALE_LOADED';
export const HIGHLIGHTS_INFO_LOADING = 'HIGHLIGHTS_INFO_LOADING';
export const HIGHLIGHTS_INFO_LOADED  = 'HIGHLIGHTS_INFO_LOADED';
export const HIGHLIGHTS_INFO_FAILED  = 'HIGHLIGHTS_INFO_FAILED';

export const VIDEOS_LOADING          = 'VIDEOS_LOADING';
export const VIDEOS_LOADED           = 'VIDEOS_LOADED';
export const VIDEOS_FAILED           = 'VIDEOS_FAILED';
export const RESET_VIDEOS            = 'RESET_VIDEOS';

export const BACKOFFICE_TOKEN_LOADING = 'BACKOFFICE_TOKEN_LOADING';
export const BACKOFFICE_TOKEN_LOADED  = 'BACKOFFICE_TOKEN_LOADED';
export const BACKOFFICE_TOKEN_FAILED  = 'BACKOFFICE_TOKEN_FAILED';

// DASHBOARD TYPES
export const ACCOUNT_INFO_LOADED    = 'ACCOUNT_INFO_LOADED';
export const PERIOD_INFO_LOADED     = 'PERIOD_INFO_LOADED';
export const UNILEVEL_LOADING       = 'UNILEVEL_LOADING';
export const UNILEVEL_LOADED        = 'UNILEVEL_LOADED';
export const UNILEVEL_FAILED        = 'UNILEVEL_FAILED';
export const BINARY_LOADING         = 'BINARY_LOADING';
export const BINARY_LOADED          = 'BINARY_LOADED';
export const BINARY_LEFT_LOADED     = 'BINARY_LEFT_LOADED';
export const BINARY_RIGHT_LOADED    = 'BINARY_RIGHT_LOADED';
export const BINARY_FAILED          = 'BINARY_FAILED';
export const AUTOCOMPLETE_LOADED    = 'AUTOCOMPLETE_LOADED';
export const LOADING_OUTER_RIGHT    = 'LOADING_OUTER_RIGHT';
export const LOADING_OUTER_LEFT     = 'LOADING_OUTER_LEFT';
export const RESET_AUTOCOMPLETE     = 'RESET_AUTOCOMPLETE';
export const AUTOCOMPLETE_LOADING   = 'AUTOCOMPLETE_LOADING';

export const LEADERBOARD_LOADING   = 'LEADERBOARD_LOADING';
export const LEADERBOARD_LOADED   = 'LEADERBOARD_LOADED';
export const LEADERBOARD_FAILED   = 'LEADERBOARD_FAILED';

export const ORG_NOTIFICATIONS_LOADING   = 'ORG_NOTIFICATIONS_LOADING';
export const ORG_NOTIFICATIONS_LOADED    = 'ORG_NOTIFICATIONS_LOADED';
export const ORG_NOTIFICATIONS_FAILED    = 'ORG_NOTIFICATIONS_FAILED';

export const UPD_DEVICE_LOCATION_SUCCESS    = 'UPD_DEVICE_LOCATION_SUCCESS';
export const UPD_DEVICE_LOCATION_FAILED    = 'UPD_DEVICE_LOCATION_FAILED';

// MEDIA TYPES
export const CHANGE_MEDIA_LANGUAGE  = 'CHANGE_MEDIA_LANGUAGE';
export const MEDIA_INFO_LOADED      = 'MEDIA_INFO_LOADED';
export const MEDIA_LIBRARY_LOADED   = 'MEDIA_LIBRARY_LOADED';

// SUPPORT TYPES
export const CREATE_TOKEN_SUCCESS   = 'CREATE_TOKEN_SUCCESS';
export const SUPPORT_FAIL_INPUTS    = 'SUPPORT_FAIL_INPUTS';
export const RESET_ERRORS_SUPPORT   = 'RESET_ERRORS_SUPPORT';

export const COUPONS_FIRST_LOADING       = 'COUPONS_FIRST_LOADING';
export const COUPONS_LOADING             = 'COUPONS_LOADING';
export const COUPONS_LOADED              = 'COUPONS_LOADED';
export const COUPONS_FAILED             = 'COUPONS_FAILED';

export const COUPONS_CREATE_LOADING      = 'COUPONS_CREATE_LOADING';
export const COUPONS_CREATE_LOADED       = 'COUPONS_CREATE_LOADED';
export const COUPONS_CREATE_FAILED       = 'COUPONS_CREATE_FAILED';

export const COUPONS_DELETE_FAILED        = 'COUPONS_DELETE_FAILED';

export const NOTIFICATION_COUNT_LOADING     = 'NOTIFICATION_COUNT_LOADING';
export const NOTIFICATION_COUNT_LOADED      = 'NOTIFICATION_COUNT_LOADED';
export const NOTIFICATION_COUNT_FAILED      = 'NOTIFICATION_COUNT_FAILED';

export const NOTIFICATIONS_FIRST_LOADING    = 'NOTIFICATIONS_FIRST_LOADING';
export const NOTIFICATIONS_LOADING          = 'NOTIFICATIONS_LOADING';
export const NOTIFICATIONS_LOADED           = 'NOTIFICATIONS_LOADED';
export const NOTIFICATIONS_FAILED           = 'NOTIFICATIONS_FAILED';

// LEADS TYPES
export const LEADS_TEXT_FILTER_CHANGED   = 'LEADS_TEXT_FILTER_CHANGED';
export const LEADS_CATEGORY_CHANGED      = 'LEADS_CATEGORY_CHANGED';
export const LEADS_LOADING               = 'LEADS_LOADING';
export const LEADS_LOADED                = 'LEADS_LOADED';
export const LEADS_FAILED                = 'LEADS_FAILED';

export const CONTACT_CREATE_SUCCESSFUL   = 'CONTACT_CREATE_SUCCESSFUL';
export const CONTACT_CREATE_FAILED       = 'CONTACT_CREATE_FAILED';
export const SELECT_CONTACT              = 'SELECT_CONTACT';
export const RESET_CONTACT_SELECTION     = 'RESET_CONTACT_SELECTION';
export const RESET_ERRORS_CONTACTS       = 'RESET_ERRORS_CONTACTS';

export const SET_CONTACT_LIST            = 'SET_CONTACT_LIST';
export const IMPORT_MULTIPLE_SUCCESSFULL = 'IMPORT_MULTIPLE_SUCCESSFULL';
export const IMPORT_MULTIPLE_LOADING     = 'IMPORT_MULTIPLE_LOADING';
export const IMPORT_MULTIPLE_FAILED      = 'IMPORT_MULTIPLE_FAILED';

// STORE TYPES
export const PRODUCTS_LOADING            = 'PRODUCTS_LOADING';
export const PRODUCTS_LOADED             = 'PRODUCTS_LOADED';
export const PRODUCTS_FAILED             = 'PRODUCTS_FAILED';

export const SWAG_PRODUCTS_LOADING       = 'SWAG_PRODUCTS_LOADING';
export const SWAG_PRODUCTS_LOADED        = 'SWAG_PRODUCTS_LOADED';
export const SWAG_PRODUCTS_FAILED        = 'SWAG_PRODUCTS_FAILED';

export const SELECT_PRODUCT              = 'SELECT_PRODUCT';
export const PRODUCT_DETAIL_LOADING      = 'PRODUCT_DETAIL_LOADING';
export const PRODUCT_DETAIL_FAILED       = 'PRODUCT_DETAIL_FAILED';

export const ADDRESS_LOADING             = 'ADDRESS_LOADING';
export const ADDRESS_SUCCESS             = 'ADDRESS_SUCCESS';
export const ADDRESS_FAILED              = 'ADDRESS_FAILED';
export const NEW_ADDRESS_SUCCESS         = 'NEW_ADDRESS_SUCCESS';
export const NEW_ADDRESS_FAILED          = 'NEW_ADDRESS_FAILED';
export const ADDRESS_DELETED_SUCCESS     = 'ADDRESS_DELETED_SUCCESS';

export const SELECT_ADDRESS              = 'SELECT_ADDRESS';
export const SELECT_ADDRESS_FAILED       = 'SELECT_ADDRESS_FAILED';
export const SELECT_BILLING_ADDRESS      = 'SELECT_BILLING_ADDRESS';
export const ADDRESS_RESET_SELECTED      = 'ADDRESS_RESET_SELECTED';

export const REGIONS_LOADING             = 'REGIONS_LOADING';
export const REGIONS_SUCCESS             = 'REGIONS_SUCCESS';
export const REGIONS_FAILED              = 'REGIONS_FAILED';

export const ADDRESS_SUGGEST_SUCCESS     = 'ADDRESS_SUGGEST_SUCCESS';
export const RESET_SUGGESTION_MODAL      = 'RESET_SUGGESTION_MODAL';
export const RESET_ADDRESS_ERRORS        = 'RESET_ADDRESS_ERRORS';
export const RESET_PURCHASE_INFO         = 'RESET_PURCHASE_INFO';

export const SELECT_PAYMENT_METHOD       = 'SELECT_PAYMENT_METHOD';
export const LOADING_PAYMENT_METHOD      = 'LOADING_PAYMENT_METHOD';
export const PAYMENT_METHOD_FAILED       = 'PAYMENT_METHOD_FAILED';

export const CARD_LOADING                = 'CARD_LOADING';
export const CARD_SUCCESS                = 'CARD_SUCCESS';
export const CARD_FAILED                 = 'CARD_FAILED';
export const SELECT_CARD                 = 'SELECT_CARD';
export const SELECT_CARD_FAILED          = 'SELECT_CARD_FAILED';
export const NEW_CARD_SUCCESS            = 'NEW_CARD_SUCCESS';
export const NEW_CARD_FAILED             = 'NEW_CARD_FAILED';

export const SAVE_CART                   = 'SAVE_CART';
export const CART_FAILED                 = 'CART_FAILED';
export const LOADING_CART                = 'LOADING_CART';
export const SAVE_TOTALS                 = 'SAVE_TOTALS';
export const LOADING_TOTALS              = 'LOADING_TOTALS';
export const TOTALS_FAILED               = 'TOTALS_FAILED';

export const LOADING_CART_QTY            = 'LOADING_CART_QTY';
export const SUCCESS_CART_QTY            = 'SUCCESS_CART_QTY';
export const FAILED_CART_QTY             = 'FAILED_CART_QTY';
export const FAILED_CART_QTY_NO_MODAL    = 'FAILED_CART_QTY_NO_MODAL';

export const ADD_TO_CART_FAILED          = 'ADD_TO_CART_FAILED';
export const ADD_TO_CART_SUCCESS         = 'ADD_TO_CART_SUCCESS';
export const ADD_TO_CART_LOADING         = 'ADD_TO_CART_LOADING';
export const RESET_CART_MODAL            = 'RESET_CART_MODAL';

export const LOADING_PURCHASE_INFO       = 'LOADING_PURCHASE_INFO';
export const PURCHASE_INFO_SUCCESS       = 'PURCHASE_INFO_SUCCESS';
export const PURCHASE_INFO_FAILED        = 'PURCHASE_INFO_FAILED';

export const PURCHASE_CONFIRMATION_LOADING  = 'PURCHASE_CONFIRMATION_LOADING';
export const PURCHASE_CONFIRMATION_SUCCESS  = 'PURCHASE_CONFIRMATION_SUCCESS';
export const PURCHASE_CONFIRMATION_FAILED   = 'PURCHASE_CONFIRMATION_FAILED';

export const RESET_DEFAULT_MODAL         = 'RESET_DEFAULT_MODAL';
export const WALLET_SAVE                 = 'WALLET_SAVE';
export const RESET_WALLET                = 'RESET_WALLET';
export const PAYMENT_METHODS_SAVE        = 'PAYMENT_METHODS_SAVE';

// REGISTER TYPES
export const PRODUCTS_REGISTER_LOADED    = 'PRODUCTS_REGISTER_LOADED';
export const UPD_REGISTER_QTY            = 'UPD_REGISTER_QTY';
export const UPD_REGISTER_AUTO_QTY       = 'UPD_REGISTER_AUTO_QTY';

export const LOADING_PACKAGES            = 'LOADING_PACKAGES';
export const SAVE_PACKAGES               = 'SAVE_PACKAGES';
export const PACKAGES_FAILED             = 'PACKAGES_FAILED';

export const LOADING_STEP_1              = 'LOADING_STEP_1';
export const SAVE_STEP1                  = 'SAVE_STEP1';
export const FAILED_STEP1                = 'FAILED_STEP1';

export const LOADING_STEP_2              = 'LOADING_STEP_2';
export const SAVE_STEP2                  = 'SAVE_STEP2';
export const FAILED_STEP2                = 'FAILED_STEP2';

export const LOADING_STEP_3              = 'LOADING_STEP_3';
export const SAVE_STEP3                  = 'SAVE_STEP3';
export const FAILED_STEP3                = 'FAILED_STEP3';

export const LOADING_STEP_4              = 'LOADING_STEP_4';
export const SAVE_STEP4                  = 'SAVE_STEP4';
export const FAILED_STEP4                = 'FAILED_STEP4';
export const RESET_STEP_4                = 'RESET_STEP_4';

export const LOADING_STEP_5              = 'LOADING_STEP_5';
export const SAVE_STEP5                  = 'SAVE_STEP5';
export const FAILED_STEP5                = 'FAILED_STEP5';

export const RESET_REGISTER_DATA         = 'RESET_REGISTER_DATA';

export const LOADING_MOBILE_MESSAGE      = 'LOADING_MOBILE_MESSAGE';
export const FAILED_MOBILE_MESSAGE       = 'FAILED_MOBILE_MESSAGE';
export const SAVE_MOBILE_TOKEN           = 'SAVE_MOBILE_TOKEN';
export const RESET_MOBILE_MESSAGE        = 'RESET_MOBILE_MESSAGE';

export const LOADING_MOBILE_VALIDATION   = 'LOADING_MOBILE_VALIDATION';
export const FAILED_MOBILE_VALIDATION    = 'FAILED_MOBILE_VALIDATION';
export const MOBILE_VALIDATION_SUCCESS   = 'MOBILE_VALIDATION_SUCCESS';

export const SAVE_COUNTRIES              = 'SAVE_COUNTRIES';

export const RESET_REGISTER_POSITION     = 'RESET_REGISTER_POSITION';
export const SAVE_REGISTER_POSITION      = 'SAVE_REGISTER_POSITION';

export const RESET_MOBILE_VALIDATION     = 'RESET_MOBILE_VALIDATION';

export const LOADING_ESTIMATED           = 'LOADING_ESTIMATED';
export const ESTIMATED_LOADED            = 'ESTIMATED_LOADED';
export const ESTIMATED_FAILED            = 'ESTIMATED_FAILED';

export const LOADING_COUPON              = 'LOADING_COUPON';
export const COUPON_LOADED               = 'COUPON_LOADED';
export const COUPON_FAILED               = 'COUPON_FAILED';

// ORDERS TYPES
export const SAVE_REFUND_DESCRIPTION     = 'SAVE_REFUND_DESCRIPTION';

export const ORDERS_FIRST_LOADING        = 'ORDERS_FIRST_LOADING';
export const ORDERS_LOADING              = 'ORDERS_LOADING';
export const ORDERS_LOADED               = 'ORDERS_LOADED';
export const ORDERS_FAILED               = 'ORDERS_FAILED';

export const ORDERS_DETAILS_LOADING      = 'ORDERS_DETAILS_LOADING';
export const ORDERS_DETAILS_LOADED       = 'ORDERS_DETAILS_LOADED';
export const ORDERS_DETAILS_FAILED       = 'ORDERS_DETAILS_FAILED';

export const ORDERS_REFUNDS_LOADED       = 'ORDERS_REFUNDS_LOADED';

export const TICKETS_FIRST_LOADING       = 'TICKETS_FIRST_LOADING';
export const TICKETS_LOADING             = 'TICKETS_LOADING';
export const TICKETS_LOADED              = 'TICKETS_LOADED';
export const TICKETS_FAILED             = 'TICKETSS_FAILED';
